version: '3.8'

services:
  php:
    build: .
    container_name: php
    volumes:
      - .:/var/www/html
    ports:
      - "9001:9000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-webserver
    volumes:
      - .:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - php
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
